### ISSUE TITLE
Updating Nightlies on MacOS

### ISSUE THREAD

**Issue by recoi1er** [DuckieTV/DuckieTV#10]
Hello I am having issue with the updater not updating when ran - newest MacOS (Monterey) - all versions.

Trying to update, I have to close out of DuckieTV through the Force Quiet option as regular Quit does nothing except it does seem to minimize the window then delete it from Applications and then run the updater installer. If it's already installed it will not install the new version!

Thanks!

**Comment by garfield69** [comment]
As you may know, Dtv uses the 3rd party product NWJS https://github.com/nwjs/nw.js which provides the run time environment and chromium headless browser so that the Dtv JavaScript can run.
The need to use the Force Quit option to properly exit DuckieTV is a re-occurring issue that comes and goes with NWJS between versions, and is often due to patch regression between versions by the NWJS team.
It's outside the control of Dtv, other that I keep an eye on the NWJS updates and try to fetch use the next version that has the fix back in place for the next Dtv Nightly build.

As for running an installer to upgrade Dtv, two suggestions:
1. check with your task manager that the DuckieTV app has not left any tasks or stubs behind and kill any you find.
2.  remember that the Dtv installer will silently fail to replace the old DuckieTV with a new one if you have not first  accessed the applications folder and dragged/dropped the DuckieTV app from the applications folder to the trashbin.
Don't ask me why, I did not write the tool.

After and installer is complete I always recommend you start Dtv and check the (i) About page and double check that the version in the About page header is the one you intended to upgrade to.

**Comment by recoi1er** [comment]
Interesting but annoying

also odd you have to delete the old app to install the new one, the only app on Mac I’ve ever had to do this with. Anyway you can have the installer delete the old version as part of the install process? Seems like an easy way around that issue for the userbase!

**Comment by garfield69** [comment]
Obviously. 
However, since the author left the project 5 years ago, I have just been keeping the lights on on the JavaScript side of Dtv.
The building of the packages, and all the rest that goes into combining NWJS and Dtv is too complex for me.
The set up, configuration and what not on the MacOS installer is made more complicated for me since I do not have a MacOS to play/test with, since the Win10 Oracle VM Virtualbox BigSur(beta) image no longer start's up (I think oracle and Apple have made a copyright agreement to avoid litigation) ;-(
