### ISSUE TITLE
Auto Download

### ISSUE THREAD

**Issue by zero77** [DuckieTV/DuckieTV#2]
The automatic torrent download is not working it either doesn’t come back with any results when in reality there are results or it just doesn’t download at all. This is the same for every torrent site you use it works at first but then stops working after a while.

**Comment by garfield69** [comment]
The DuckieTV Demo version uses a third party service to work around cross-domain limitations and can be broken at any time.

Due to the restrictions of the 3rd party service, downloads, torrent integrations, and some other features don't work.

This online demo version is not meant to provide a fully working all-features enabled version of DuckieTV. It really just gives the user a way of exploring the GUI to see what is available in the downloadable version.
