### ISSUE TITLE
Shows are not refreshing unless done Manually

### ISSUE THREAD

**Issue by Infallibleman** [DuckieTV/DuckieTV#8]
I have run into this issue with 3-4 shows.  Duckie TV does not refresh the show, so its not aware of the episodes that are being aired.  

Please see the attached video clip for the issue and the manual refresh to get it going

https://user-images.githubusercontent.com/36009107/115774744-9586b080-a377-11eb-839b-ea837d45e276.mp4

**Comment by garfield69** [comment]
Several things: 
1. make sure you are on the latest Dtv Nightly Standalone from https://github.com/DuckieTV/Nightlies/releases as some earlier releases did not have the Trakt.tv rate limiting handler. This would fit the symptom you describe, as the regular Dtv bulk episode update could hit the limiter and prevent all the shows getting updated. Where as a single show refresh might slide under the rate limit and succeed.
2. Trakt.tv are in the middle of switching their primary data source from tvdb to tmdb. It may be that tmdb is not being kept as up to date as tvdb was, which in turn could lead to trakt.tv's API servers not being as up to date.
3. The default setting for Dtv is to access the Trakt.tv servers once every 12 hours. Try adjusting that setting to fetch updates hourly. **dtv>settings>trakt.tv>trakt.tv update period**. This may help your Dtv to fetch updates more regularly, especially due to item 2.
