### ISSUE TITLE
shows stopping appearing in in the calendar

### ISSUE THREAD

**Issue by recoi1er** [DuckieTV/DuckieTV#9]
Shows like Mayans and Shameless just stop after a certain episode, other shows display the whole season no issues. Have tried updating to most recent nightlies a few times over the past couple months but that does no change things. I have done "refresh all series now" a few times as well!

Any ideas?

**Comment by garfield69** [comment]
If your Dtv Standalone Nightly is a few months old then please update to the latest from https://github.com/DuckieTV/Nightlies/releases/tag/nightly-202104242304

Older Dtv Standalone Nightly ran into a Trakt.tv API server rate limit which meant that during the Dtv update fetch process you might hit the Trakt.tv limiter after a certain number of shows got processed, then once those shows were skipped, pick up updates for more shows before hitting the limiter again.
That pattern could cause some shows to fail to get fresh updates on a fairly regular pattern.

Looking back at the release log, the fix went in around the middle of February.
More recently, Trakt.tv stopped using TVDB as their primary data source for shows and started using TMDB exclusively instead.
The fix to cope with that was completed around the middle of March.

However, since then I have noticed that TMDB appears to not be kept as up to date as frequently as TVDB is, so depending on your Trakt.tv update period setting, it could be as much as 24 hours before you get the very latest show data.
For this reason I recommend changing your **dtv->settings->trakt.tv->trakt.tv update period** from the default 12 hours to **1 hour**, to maximise the chances of getting the latest data.

I find my shows are being kept up to date on https://github.com/DuckieTV/Nightlies/releases/tag/nightly-202104242304

If you find yours are still not getting the updates you expect while on this release, then the next thing to do is check the console logs regularly for Trakt.tv server errors to see if that accounts for the issue. **F12** opens the _development tools_ window, and the **console** tab has the current session log.
Ignore the _fanart 404 or 50x_ errors, those are common and don't impact trakt.tv show updates.

Lastly, you did not specify what platform you are on, but if you are on OSx then remember to first move the DuckieTV app from the applications folder to the trashbin before running the Dtv installer, or your code will not get updated.

Check the Dtv **About** side panel by clicking on the **(i)** icon near the bottom left of the main DTV page to confirm that you are on the correct version.

I'm closing this, but will reopen if your feedback reports ongoing problem and I can try to help figure out what might be going on.

**Comment by recoi1er** [comment]
Hi! Thanks for the reply!

I am on MacOS and totally forgot to delete before installing the last few times, but I did that just now and installed the newest nightly and still am missing shows. on Version 202104242304 from the About side panel. I changed the trakt update interval to 1 hour, it showed it was updating my show's but it didn't add any of the missing ones.

I am missing Mayans still for instance the last 3 weeks.

<img width="812" alt="Screen Shot 2021-04-27 at 19 55 11" src="https://user-images.githubusercontent.com/19810634/116339830-fd336600-a792-11eb-8142-243eab93c75d.png">


I checked the console and this is what I have, not sure why it fails to connect to qbittorrent with credentials (this doesn't change if I have "no auth on localhost" enabled or not and then it connects shortly after that.

`deps.js:92 DuckieTV quack!

app.js:8394 Registering torrent client: Aria2
app.js:8394 Registering torrent client: BiglyBT
app.js:8394 Registering torrent client: Deluge
app.js:8394 Registering torrent client: qBittorrent (pre3.2)
app.js:8394 Registering torrent client: qBittorrent 3.2+
app.js:8394 Registering torrent client: Ktorrent
app.js:8394 Registering torrent client: rTorrent
app.js:8394 Registering torrent client: Tixati
app.js:8394 Registering torrent client: Transmission
app.js:8394 Registering torrent client: tTorrent
app.js:8394 Registering torrent client: uTorrent Web UI
app.js:8394 Registering torrent client: Vuze
app.js:8394 Registering torrent client: None
app.js:11130 SettingsService.changeLanguage en_us en_us
app.js:8324 The next autoBackup is scheduled for Fri May 07 2021 10:02:17 GMT-0700 (Pacific Daylight Time)
app.js:10573 Next SNRT update is due after  Wed Apr 28 2021 19:49:53 GMT-0700 (Pacific Daylight Time)
app.js:10574 Fetched SNRT name and date exceptions, and TraktTvdbXref from localStorage.
app.js:10725 Initializing Xross Entity Mapping (http://thexem.de/) service for Scene Name episode format.
app.js:10653 Fetched localstorage Xem series list:  Array(866)
app.js:10655 Fetched localstorage Xem series alias map: Object
app.js:11553 Enabling torrent auto-stop!
app.js:16202 Fetched trackers fall back list from localStorage.
app.js:15994 Updating torrent search engine ThePirateBay
app.js:15994 Updating torrent search engine 1337x
app.js:15994 Updating torrent search engine ETag
app.js:15994 Updating torrent search engine ETTV
app.js:15994 Updating torrent search engine EXT
app.js:15994 Updating torrent search engine EzTV.ag
app.js:15994 Updating torrent search engine Idope
app.js:15994 Updating torrent search engine IsoHunt2
app.js:15994 Updating torrent search engine KATws
app.js:15994 Updating torrent search engine LimeTorrents
app.js:15994 Updating torrent search engine Nyaa
app.js:15994 Updating torrent search engine RarBG
app.js:15994 Updating torrent search engine ShowRSS
app.js:15994 Updating torrent search engine TorrentDownloads
app.js:15994 Updating torrent search engine TGx
app.js:15994 Updating torrent search engine TorrentZ2
app.js:15994 Updating torrent search engine Zooqle
app.js:11297 Register new storage sync target! TraktTVStorageSyncTarget
user:password@localhost:8080/version/api:1 Failed to load resource: the server responded with a status of 404 (Not Found)
app.js:11769 Unable to connect to qBittorrent 3.2+ Retry in 15 seconds
deps.js:2397 Possibly unhandled rejection: Not connected.
(anonymous) @ deps.js:2397
app.js:9153 Initializing AutoDownload Service!
app.js:19018 Not performing TraktTV update check. Already done within the last 1 hour(s).
app.js:19031 Not performing TraktTV trending update check. Last done Mon Apr 26 2021 19:48:29 GMT-0700 (Pacific Daylight Time)
app.js:9126 Caught TorrentClient connected event! starting AutoDownload check!
app.js:11753 qBittorrent 3.2+ connected!`

**Comment by garfield69** [comment]
your log looks perfectly normal.
it takes Dtv two goes at connecting to the latest qBt, because the first time it connects it tries using the older API protocol (if we tries the new API protocol first, qBt would appear to connect but be unresponsive later). 
So Dtv then fails to connect first time, and on the second go 15 secs later it uses the New API and connects.

I see that the log you provided was not one where the trakt.tv update was in progress, so the next time you get the update progress bar on your gui flick to the console to check the trakt.tv update progress from there, looking for any signs of errors. 

I just loaded mayans m.c. fresh and this is the season 3 capture
![image](https://user-images.githubusercontent.com/6933240/116342837-6371c480-a837-11eb-9eda-3a40115efff9.png)

Does your episode list side panel for that series only go up to s03e05 like the view of your calendar?

**Comment by garfield69** [comment]
My Dtv fetched s03e09 of Mayans M.C. just now.
Is yours still on s03e05 in the series details episode list?

**Comment by recoi1er** [comment]
All of a sudden it loaded and so did a bunch of other shows I didn’t even know were on! 

Thanks for the help!


Thank you,

Oliver Shipp
